version: "3.8"

services:
  db:
    image: postgres:16
    container_name: desafio3-db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: desafio3db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - desafio3-net

  cache:
    image: redis:7
    container_name: desafio3-cache
    networks:
      - desafio3-net

  web:
    build: ./web
    container_name: desafio3-web
    ports:
      - "8000:5000"
    environment:
      DB_HOST: db
      DB_NAME: desafio3db
      DB_USER: usuario
      DB_PASSWORD: senha123
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - db
      - cache
    networks:
      - desafio3-net

volumes:
  db-data:

networks:
  desafio3-net:
